export const Projects = [
  {
    name: "E-Commerce",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: true,
      firebase: true,
      stripe: true,
      tailwind: false,
      sanity: false,
    },
    gitlink: "",
    demolink: "",
  },
  {
    name: "Content AI",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
    gitlink: "",
    demolink: "",
  },
  {
    name: "My Portfolio",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
    gitlink: "",
    demolink: "",
  },
  {
    name: "DApp Crowdfunding",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
    gitlink: "",
    demolink: "",
  },
  {
    name: "Chat App",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
    gitlink: "",
    demolink: "",
  },
];
